stages:
  - build

build:
  image: texlive/texlive:latest
  stage: build
  script:
    - cd src
    - pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf -output-dir=../ main.tex
  after_script:
    - cat out/main.log
  artifacts:
    paths:
      - main.pdf
