stages:
  - build
  - deploy

include:
  - component: $CI_SERVER_FQDN/infrastructure/latex-build-base/latex-build@1.0.0
    inputs:
      stage: build

latex-build:
  before_script:
    - cd "${CI_PROJECT_DIR}/src"

deploy:
  stage: deploy
  trigger:
    project: dylan/resume-website
